### ISSUE TITLE
The model: `code-davinci-002` does not exist Retry.

### ISSUE THREAD

**Issue by wbbeyourself** [shuaichenchang/prompt-text-to-sql#2]
I just found CodeX has been deprecated by OpenAI. See docs:

https://platform.openai.com/docs/guides/code/code-completion-deprecated

So, only ChatGPT-0301 version results can be reproduced, which will also be deprecated in less than 3 months.

**Comment by shuaichenchang** [comment]
Thank you for your interest! Codex is available on Azure https://learn.microsoft.com/en-us/azure/cognitive-services/openai/concepts/models or on OpenAI with research request https://openai.com/form/researcher-access-program. 
We plan to rerun our experiments with ChatGPT-0613 to keep our results updated.
